# Generated by Django 5.1.1 on 2024-10-08 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chaleco',
            fields=[
                ('serial', models.IntegerField(primary_key=True, serialize=False)),
                ('beneficiario_cedula', models.ForeignKey(db_column='cedula', on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.beneficiario')),
            ],
        ),
    ]
