# Generated by Django 5.1.1 on 2024-10-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=255, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
            ],
        ),
    ]
